import React from 'react';

interface SEOKeywordsProps {
  keywords?: string[];
  lsiKeywords?: string[];
}

// LSI (Latent Semantic Indexing) keywords for better SEO
export const defaultLSIKeywords = {
  sr: [
    // Primary keywords
    'web development Serbia',
    'izrada sajtova Beograd',
    'web dizajn Srbija',
    'aplikacije za mobilne telefone',
    'digitalna agencija',
    
    // LSI keywords
    'responsivni web dizajn',
    'SEO optimizacija sajta',
    'WordPress development',
    'React aplikacije',
    'Next.js development',
    'e-commerce rešenja',
    'online prodavnica',
    'UI/UX dizajn',
    'frontend development',
    'backend development',
    'full stack developer',
    'Node.js development',
    'JavaScript programiranje',
    'TypeScript development',
    'web hosting Srbija',
    'održavanje sajtova',
    'digitalni marketing',
    'Google Ads kampanje',
    'brza izrada sajta',
    'profesionalni web sajt',
    'biznis aplikacije',
    'custom software development',
    'API integracije',
    'Progressive Web Apps',
    'Single Page Applications',
    'mobilne aplikacije Android',
    'mobilne aplikacije iOS',
    'cross-platform development',
    'cloud solutions',
    'web sigurnost',
    'SSL sertifikati',
    'brzina učitavanja sajta',
    'Core Web Vitals',
    'Google PageSpeed',
    'konverzija posetilaca',
    'user experience',
    'pristupačnost web sajta',
    'WCAG compliance',
    'responsive design',
    'mobile-first approach',
    'agile development',
    'sprint planning',
    'tech stack moderni',
    'mikroservisi',
    'serverless architecture',
    'headless CMS',
    'Jamstack',
    'GraphQL API',
    'REST API',
    'web komponente',
    'Material Design',
    'Bootstrap framework',
    'Tailwind CSS',
    'Git version control',
    'CI/CD pipeline',
    'DevOps practices',
    'Docker containers',
    'Kubernetes orchestration',
    'test driven development',
    'quality assurance',
    'bug fixing',
    'code review',
    'technical documentation',
    'project management',
    'Scrum methodology',
    'web analytics',
    'Google Analytics 4',
    'conversion tracking',
    'A/B testing',
    'heat mapping',
    'user behavior analysis'
  ],
  en: [
    // Primary keywords  
    'web development agency',
    'website design company',
    'custom web solutions',
    'mobile app development',
    'digital transformation',
    
    // LSI keywords
    'responsive web design',
    'SEO optimization services',
    'WordPress development',
    'React development company',
    'Next.js experts',
    'e-commerce solutions',
    'online store development',
    'UI/UX design services',
    'frontend developers',
    'backend developers',
    'full stack development',
    'Node.js developers',
    'JavaScript programming',
    'TypeScript experts',
    'web hosting services',
    'website maintenance',
    'digital marketing agency',
    'Google Ads management',
    'fast website development',
    'professional website',
    'business applications',
    'custom software solutions',
    'API integration services',
    'Progressive Web Apps',
    'Single Page Applications',
    'Android app development',
    'iOS app development',
    'cross-platform apps',
    'cloud computing solutions',
    'web security services',
    'SSL certificates',
    'website speed optimization',
    'Core Web Vitals optimization',
    'Google PageSpeed insights',
    'conversion rate optimization',
    'user experience design',
    'web accessibility services',
    'WCAG compliance',
    'responsive design services',
    'mobile-first development',
    'agile development process',
    'sprint planning services',
    'modern tech stack',
    'microservices architecture',
    'serverless computing',
    'headless CMS solutions',
    'Jamstack development',
    'GraphQL API development',
    'REST API services',
    'web components development',
    'Material Design implementation',
    'Bootstrap development',
    'Tailwind CSS experts',
    'Git version control',
    'CI/CD implementation',
    'DevOps consulting',
    'Docker containerization',
    'Kubernetes deployment',
    'test driven development',
    'quality assurance testing',
    'bug fixing services',
    'code review process',
    'technical documentation',
    'project management services',
    'Scrum methodology',
    'web analytics setup',
    'Google Analytics 4',
    'conversion tracking setup',
    'A/B testing services',
    'heat mapping analysis',
    'user behavior tracking'
  ],
  de: [
    // Primary keywords
    'Webentwicklung Agentur',
    'Website Design Firma',
    'maßgeschneiderte Weblösungen',
    'Mobile App Entwicklung',
    'digitale Transformation',
    
    // LSI keywords
    'responsives Webdesign',
    'SEO Optimierung Dienste',
    'WordPress Entwicklung',
    'React Entwicklung',
    'Next.js Experten',
    'E-Commerce Lösungen',
    'Online Shop Entwicklung',
    'UI/UX Design Dienste',
    'Frontend Entwickler',
    'Backend Entwickler',
    'Full Stack Entwicklung',
    'Node.js Entwickler',
    'JavaScript Programmierung',
    'TypeScript Experten',
    'Webhosting Dienste',
    'Website Wartung',
    'Digital Marketing Agentur',
    'Google Ads Verwaltung',
    'schnelle Website Entwicklung',
    'professionelle Website',
    'Geschäftsanwendungen',
    'maßgeschneiderte Software',
    'API Integration Dienste',
    'Progressive Web Apps',
    'Single Page Applications',
    'Android App Entwicklung',
    'iOS App Entwicklung',
    'plattformübergreifende Apps',
    'Cloud Computing Lösungen',
    'Web Sicherheitsdienste',
    'SSL Zertifikate',
    'Website Geschwindigkeitsoptimierung',
    'Core Web Vitals Optimierung',
    'Google PageSpeed Insights',
    'Conversion Rate Optimierung',
    'User Experience Design',
    'Web Barrierefreiheit',
    'WCAG Konformität',
    'responsives Design Dienste',
    'Mobile-First Entwicklung',
    'agile Entwicklung',
    'Sprint Planung',
    'moderner Tech Stack',
    'Microservices Architektur',
    'Serverless Computing',
    'Headless CMS Lösungen',
    'Jamstack Entwicklung',
    'GraphQL API Entwicklung',
    'REST API Dienste',
    'Web Komponenten',
    'Material Design',
    'Bootstrap Entwicklung',
    'Tailwind CSS Experten',
    'Git Versionskontrolle',
    'CI/CD Implementierung',
    'DevOps Beratung',
    'Docker Container',
    'Kubernetes Bereitstellung',
    'testgetriebene Entwicklung',
    'Qualitätssicherung',
    'Fehlerbehebung',
    'Code Review Prozess',
    'technische Dokumentation',
    'Projektmanagement',
    'Scrum Methodik',
    'Web Analytics Setup',
    'Google Analytics 4',
    'Conversion Tracking',
    'A/B Testing Dienste',
    'Heatmap Analyse',
    'Nutzerverhalten Tracking'
  ]
};

export const SEOKeywords: React.FC<SEOKeywordsProps> = ({ 
  keywords = [], 
  lsiKeywords = [] 
}) => {
  // This component doesn't render anything visible
  // It's used for semantic HTML structure
  return null;
};

// Helper function to get relevant keywords for a page
export const getPageKeywords = (
  pageName: string, 
  language: 'sr' | 'en' | 'de' = 'sr'
): string[] => {
  const baseKeywords = defaultLSIKeywords[language];
  
  // Add page-specific keywords
  const pageSpecificKeywords: Record<string, string[]> = {
    home: baseKeywords.slice(0, 30),
    services: [...baseKeywords.slice(10, 25), ...baseKeywords.slice(40, 50)],
    portfolio: [...baseKeywords.slice(5, 15), ...baseKeywords.slice(35, 45)],
    about: baseKeywords.slice(0, 20),
    contact: baseKeywords.slice(0, 15),
    blog: [...baseKeywords.slice(20, 35), ...baseKeywords.slice(50, 60)]
  };
  
  return pageSpecificKeywords[pageName] || baseKeywords.slice(0, 25);
};

export default SEOKeywords;